-- SolarSage hardening migration (audit FIX-05 / SEC-08)
-- Safe to apply on the existing schema. Generated by the codebase audit.

-- PERF-02 / FAIL-06: index the column every record query filters and orders by.
CREATE INDEX IF NOT EXISTS idx_customer_info_user_id_created_at
  ON public.customer_info (user_id, created_at DESC);

-- SEC-08: pin search_path on the SECURITY DEFINER trigger function to prevent
-- search-path hijacking. (Function body unchanged.)
ALTER FUNCTION public.handle_new_user() SET search_path = public, pg_temp;

-- NOTE (not auto-applied here — requires data backfill, do in a planned migration):
--   * Convert customer_info.consumption/generation/savings from TEXT to NUMERIC.
--   * Privatize the `pdfs` storage bucket and add per-user storage RLS (SEC-01).
-- See docs/audits/ for the full remediation plan.
